---
title: "Bringing Auto-diff to R packages"
subtitle: ""
author: ["Michael Komodromos, Imperial College London"]
date: "`r Sys.Date()`"
bibliography: "refs.bib"
output:
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "")

knitr::knit_hooks$set(
  plot = function(x, options) {
    hugoopts <- options$hugoopts
    paste0(
      "{", "{<figure src=", # the original code is simpler
      # but here I need to escape the shortcode!
      '"', x, '" ',
      if (!is.null(hugoopts)) {
        glue::glue_collapse(
          glue::glue('{names(hugoopts)}="{hugoopts}"'),
          sep = " "
        )
      },
      ">}}\n"
    )
  }
)

```


## Abstract

We demonstrate the use of a C++ algorithmic differentiation library and show
how it can be used with the R programming language to solve problems in optimization, 
MCMC and beyond. In particular, we show how gradients produced with algorithmic differentiation
can be used with R's built in optimization routines. We hope such integrations will enable package
developers to produce robust efficient code by overcoming the need to produce
functions that compute gradients.

### Keywords

R package development, algorithmic-differentiation

## Introduction

Algorithm differentiation (AD), also known as automatic-differentiation, has found wide use in machine leaning and statistics. As the name suggest AD allows for the automatic computation of derivatives, without the need to painstakingly derive there expressions.


## Methods

AD allows for fast computation of function gradients through repeated application of the chain rule. There are two main modes in AD, *forward mode* and *reverse mode*. For a detailed introduction to AD we direct the reader to @Gebremedhin2020.

Throughout our explanation of forward and reverse mode AD we will consider the function
$$
f(x_1, x_2) = \exp(x_1 + x_2) + \sin(x_1 + x_2),
$$
where $x_1,x_2 \in \mathbb{R}$.


### Forward mode

...

### Reverse mode

...

## Examples



## Conclusions


## Declarations

### List of abbreviations

 - AD: algorithmic differentiation

### Availability of supporting source code and requirements

-   Project name: rad
-   Project home page: https://github.com/mkomod/rad
-   Operating system(s): Platform Independent
-   Programming language: R, C++
-   License: GNU GPL

# References

